-- SUPERSNAKE — Supabase SQL (schema + RLS + seed template)
-- Run this in Supabase Dashboard -> SQL Editor.

-- 1) Tables
create table if not exists public.profiles (
  id uuid not null references auth.users (id) on delete cascade,
  username text,
  avatar_url text,
  updated_at timestamptz not null default now(),
  primary key (id)
);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  username text,
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

create index if not exists scores_user_id_idx on public.scores (user_id);
create index if not exists scores_score_idx on public.scores (score desc);
create index if not exists scores_created_at_idx on public.scores (created_at desc);

-- 2) Triggers
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

-- Auto-create a profile row for each new auth user (optional but recommended)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      case when new.email is null then null else split_part(new.email, '@', 1) end
    ),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- 3) Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.scores enable row level security;

-- Public read (so leaderboards work without login too)
drop policy if exists "profiles_select_public" on public.profiles;
create policy "profiles_select_public"
on public.profiles
for select
using (true);

drop policy if exists "scores_select_public" on public.scores;
create policy "scores_select_public"
on public.scores
for select
using (true);

-- Users can manage their own profile
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- Users can submit only their own scores
drop policy if exists "scores_insert_own" on public.scores;
create policy "scores_insert_own"
on public.scores
for insert
with check (auth.uid() = user_id);

-- (Optional) allow users to delete their own scores
-- drop policy if exists "scores_delete_own" on public.scores;
-- create policy "scores_delete_own"
-- on public.scores
-- for delete
-- using (auth.uid() = user_id);

-- 4) Seed template (needs real auth.users UUIDs)
-- IMPORTANT:
-- - Because `profiles.id` and `scores.user_id` reference `auth.users(id)`,
--   you MUST create users first (Google sign-in or email) then copy their UUIDs.
--
-- Example:
-- insert into public.profiles (id, username)
-- values
--   ('REPLACE_WITH_REAL_AUTH_USER_UUID_1', 'DemoPlayer1'),
--   ('REPLACE_WITH_REAL_AUTH_USER_UUID_2', 'DemoPlayer2')
-- on conflict (id) do update set username = excluded.username;
--
-- insert into public.scores (user_id, username, score)
-- values
--   ('REPLACE_WITH_REAL_AUTH_USER_UUID_1', 'DemoPlayer1', 120),
--   ('REPLACE_WITH_REAL_AUTH_USER_UUID_2', 'DemoPlayer2', 95);

